module chipyard_wrapper(
    input         axi4_mmio_0_awready,
    output        axi4_mmio_0_awvalid,
    output  [3:0] axi4_mmio_0_awid,
    output [30:0] axi4_mmio_0_awaddr,
    output  [7:0] axi4_mmio_0_awlen,
    output  [2:0] axi4_mmio_0_awsize,
    output  [1:0] axi4_mmio_0_awburst,
    output        axi4_mmio_0_awlock,
    output  [3:0] axi4_mmio_0_awcache,
    output  [2:0] axi4_mmio_0_awprot,
    output  [3:0] axi4_mmio_0_awqos,
    input         axi4_mmio_0_wready,
    output        axi4_mmio_0_wvalid,
    output [63:0] axi4_mmio_0_wdata,
    output  [7:0] axi4_mmio_0_wstrb,
    output        axi4_mmio_0_wlast,
    output        axi4_mmio_0_bready,
    input         axi4_mmio_0_bvalid,
    input   [3:0] axi4_mmio_0_bid,
    input   [1:0] axi4_mmio_0_bresp,
    input         axi4_mmio_0_arready,
    output        axi4_mmio_0_arvalid,
    output  [3:0] axi4_mmio_0_arid,
    output [30:0] axi4_mmio_0_araddr,
    output  [7:0] axi4_mmio_0_arlen,
    output  [2:0] axi4_mmio_0_arsize,
    output  [1:0] axi4_mmio_0_arburst,
    output        axi4_mmio_0_arlock,
    output  [3:0] axi4_mmio_0_arcache,
    output  [2:0] axi4_mmio_0_arprot,
    output  [3:0] axi4_mmio_0_arqos,
    output        axi4_mmio_0_rready,
    input         axi4_mmio_0_rvalid,
    input   [3:0] axi4_mmio_0_rid,
    input  [63:0] axi4_mmio_0_rdata,
    input   [1:0] axi4_mmio_0_rresp,
    input         axi4_mmio_0_rlast,
    output        axi4_fbus_0_awready,
    input         axi4_fbus_0_awvalid,
    input   [7:0] axi4_fbus_0_awid,
    input  [32:0] axi4_fbus_0_awaddr,
    input   [7:0] axi4_fbus_0_awlen,
    input   [2:0] axi4_fbus_0_awsize,
    input   [1:0] axi4_fbus_0_awburst,
    input         axi4_fbus_0_awlock,
    input   [3:0] axi4_fbus_0_awcache,
    input   [2:0] axi4_fbus_0_awprot,
    input   [3:0] axi4_fbus_0_awqos,
    output        axi4_fbus_0_wready,
    input         axi4_fbus_0_wvalid,
    input  [63:0] axi4_fbus_0_wdata,
    input   [7:0] axi4_fbus_0_wstrb,
    input         axi4_fbus_0_wlast,
    input         axi4_fbus_0_bready,
    output        axi4_fbus_0_bvalid,
    output  [7:0] axi4_fbus_0_bid,
    output  [1:0] axi4_fbus_0_bresp,
    output        axi4_fbus_0_arready,
    input         axi4_fbus_0_arvalid,
    input   [7:0] axi4_fbus_0_arid,
    input  [32:0] axi4_fbus_0_araddr,
    input   [7:0] axi4_fbus_0_arlen,
    input   [2:0] axi4_fbus_0_arsize,
    input   [1:0] axi4_fbus_0_arburst,
    input         axi4_fbus_0_arlock,
    input   [3:0] axi4_fbus_0_arcache,
    input   [2:0] axi4_fbus_0_arprot,
    input   [3:0] axi4_fbus_0_arqos,
    input         axi4_fbus_0_rready,
    output        axi4_fbus_0_rvalid,
    output  [7:0] axi4_fbus_0_rid,
    output [63:0] axi4_fbus_0_rdata,
    output  [1:0] axi4_fbus_0_rresp,
    output        axi4_fbus_0_rlast,
    input         clock_clock,
    input         reset,
    input         axi4_mem_0_awready,
    output        axi4_mem_0_awvalid,
    output  [3:0] axi4_mem_0_awid,
    output [32:0] axi4_mem_0_awaddr,
    output  [7:0] axi4_mem_0_awlen,
    output  [2:0] axi4_mem_0_awsize,
    output  [1:0] axi4_mem_0_awburst,
    output        axi4_mem_0_awlock,
    output  [3:0] axi4_mem_0_awcache,
    output  [2:0] axi4_mem_0_awprot,
    output  [3:0] axi4_mem_0_awqos,
    input         axi4_mem_0_wready,
    output        axi4_mem_0_wvalid,
    output [63:0] axi4_mem_0_wdata,
    output  [7:0] axi4_mem_0_wstrb,
    output        axi4_mem_0_wlast,
    output        axi4_mem_0_bready,
    input         axi4_mem_0_bvalid,
    input   [3:0] axi4_mem_0_bid,
    input   [1:0] axi4_mem_0_bresp,
    input         axi4_mem_0_arready,
    output        axi4_mem_0_arvalid,
    output  [3:0] axi4_mem_0_arid,
    output [32:0] axi4_mem_0_araddr,
    output  [7:0] axi4_mem_0_arlen,
    output  [2:0] axi4_mem_0_arsize,
    output  [1:0] axi4_mem_0_arburst,
    output        axi4_mem_0_arlock,
    output  [3:0] axi4_mem_0_arcache,
    output  [2:0] axi4_mem_0_arprot,
    output  [3:0] axi4_mem_0_arqos,
    output        axi4_mem_0_rready,
    input         axi4_mem_0_rvalid,
    input   [3:0] axi4_mem_0_rid,
    input  [63:0] axi4_mem_0_rdata,
    input   [1:0] axi4_mem_0_rresp,
    input         axi4_mem_0_rlast,
    input   [3:0] ext_interrupts
);

ChipTop ct_inst(
    .axi4_mmio_0_clock(),
    .axi4_mmio_0_bits_aw_ready(axi4_mmio_0_awready),
    .axi4_mmio_0_bits_aw_valid(axi4_mmio_0_awvalid),
    .axi4_mmio_0_bits_aw_bits_id(axi4_mmio_0_awid),
    .axi4_mmio_0_bits_aw_bits_addr(axi4_mmio_0_awaddr),
    .axi4_mmio_0_bits_aw_bits_len(axi4_mmio_0_awlen),
    .axi4_mmio_0_bits_aw_bits_size(axi4_mmio_0_awsize),
    .axi4_mmio_0_bits_aw_bits_burst(axi4_mmio_0_awburst),
    .axi4_mmio_0_bits_aw_bits_lock(axi4_mmio_0_awlock),
    .axi4_mmio_0_bits_aw_bits_cache(axi4_mmio_0_awcache),
    .axi4_mmio_0_bits_aw_bits_prot(axi4_mmio_0_awprot),
    .axi4_mmio_0_bits_aw_bits_qos(axi4_mmio_0_awqos),
    .axi4_mmio_0_bits_w_ready(axi4_mmio_0_wready),
    .axi4_mmio_0_bits_w_valid(axi4_mmio_0_wvalid),
    .axi4_mmio_0_bits_w_bits_data(axi4_mmio_0_wdata),
    .axi4_mmio_0_bits_w_bits_strb(axi4_mmio_0_wstrb),
    .axi4_mmio_0_bits_w_bits_last(axi4_mmio_0_wlast),
    .axi4_mmio_0_bits_b_ready(axi4_mmio_0_bready),
    .axi4_mmio_0_bits_b_valid(axi4_mmio_0_bvalid),
    .axi4_mmio_0_bits_b_bits_id(axi4_mmio_0_bid),
    .axi4_mmio_0_bits_b_bits_resp(axi4_mmio_0_bresp),
    .axi4_mmio_0_bits_ar_ready(axi4_mmio_0_arready),
    .axi4_mmio_0_bits_ar_valid(axi4_mmio_0_arvalid),
    .axi4_mmio_0_bits_ar_bits_id(axi4_mmio_0_arid),
    .axi4_mmio_0_bits_ar_bits_addr(axi4_mmio_0_araddr),
    .axi4_mmio_0_bits_ar_bits_len(axi4_mmio_0_arlen),
    .axi4_mmio_0_bits_ar_bits_size(axi4_mmio_0_arsize),
    .axi4_mmio_0_bits_ar_bits_burst(axi4_mmio_0_arburst),
    .axi4_mmio_0_bits_ar_bits_lock(axi4_mmio_0_arlock),
    .axi4_mmio_0_bits_ar_bits_cache(axi4_mmio_0_arcache),
    .axi4_mmio_0_bits_ar_bits_prot(axi4_mmio_0_arprot),
    .axi4_mmio_0_bits_ar_bits_qos(axi4_mmio_0_arqos),
    .axi4_mmio_0_bits_r_ready(axi4_mmio_0_rready),
    .axi4_mmio_0_bits_r_valid(axi4_mmio_0_rvalid),
    .axi4_mmio_0_bits_r_bits_id(axi4_mmio_0_rid),
    .axi4_mmio_0_bits_r_bits_data(axi4_mmio_0_rdata),
    .axi4_mmio_0_bits_r_bits_resp(axi4_mmio_0_rresp),
    .axi4_mmio_0_bits_r_bits_last(axi4_mmio_0_rlast),
    .axi4_fbus_0_clock(),
    .axi4_fbus_0_bits_aw_ready(axi4_fbus_0_awready),
    .axi4_fbus_0_bits_aw_valid(axi4_fbus_0_awvalid),
    .axi4_fbus_0_bits_aw_bits_id(axi4_fbus_0_awid),
    .axi4_fbus_0_bits_aw_bits_addr(axi4_fbus_0_awaddr),
    .axi4_fbus_0_bits_aw_bits_len(axi4_fbus_0_awlen),
    .axi4_fbus_0_bits_aw_bits_size(axi4_fbus_0_awsize),
    .axi4_fbus_0_bits_aw_bits_burst(axi4_fbus_0_awburst),
    .axi4_fbus_0_bits_aw_bits_lock(axi4_fbus_0_awlock),
    .axi4_fbus_0_bits_aw_bits_cache(axi4_fbus_0_awcache),
    .axi4_fbus_0_bits_aw_bits_prot(axi4_fbus_0_awprot),
    .axi4_fbus_0_bits_aw_bits_qos(axi4_fbus_0_awqos),
    .axi4_fbus_0_bits_w_ready(axi4_fbus_0_wready),
    .axi4_fbus_0_bits_w_valid(axi4_fbus_0_wvalid),
    .axi4_fbus_0_bits_w_bits_data(axi4_fbus_0_wdata),
    .axi4_fbus_0_bits_w_bits_strb(axi4_fbus_0_wstrb),
    .axi4_fbus_0_bits_w_bits_last(axi4_fbus_0_wlast),
    .axi4_fbus_0_bits_b_ready(axi4_fbus_0_bready),
    .axi4_fbus_0_bits_b_valid(axi4_fbus_0_bvalid),
    .axi4_fbus_0_bits_b_bits_id(axi4_fbus_0_bid),
    .axi4_fbus_0_bits_b_bits_resp(axi4_fbus_0_bresp),
    .axi4_fbus_0_bits_ar_ready(axi4_fbus_0_arready),
    .axi4_fbus_0_bits_ar_valid(axi4_fbus_0_arvalid),
    .axi4_fbus_0_bits_ar_bits_id(axi4_fbus_0_arid),
    .axi4_fbus_0_bits_ar_bits_addr(axi4_fbus_0_araddr),
    .axi4_fbus_0_bits_ar_bits_len(axi4_fbus_0_arlen),
    .axi4_fbus_0_bits_ar_bits_size(axi4_fbus_0_arsize),
    .axi4_fbus_0_bits_ar_bits_burst(axi4_fbus_0_arburst),
    .axi4_fbus_0_bits_ar_bits_lock(axi4_fbus_0_arlock),
    .axi4_fbus_0_bits_ar_bits_cache(axi4_fbus_0_arcache),
    .axi4_fbus_0_bits_ar_bits_prot(axi4_fbus_0_arprot),
    .axi4_fbus_0_bits_ar_bits_qos(axi4_fbus_0_arqos),
    .axi4_fbus_0_bits_r_ready(axi4_fbus_0_rready),
    .axi4_fbus_0_bits_r_valid(axi4_fbus_0_rvalid),
    .axi4_fbus_0_bits_r_bits_id(axi4_fbus_0_rid),
    .axi4_fbus_0_bits_r_bits_data(axi4_fbus_0_rdata),
    .axi4_fbus_0_bits_r_bits_resp(axi4_fbus_0_rresp),
    .axi4_fbus_0_bits_r_bits_last(axi4_fbus_0_rlast),
    .clock_uncore(clock_clock),
    .reset_io(reset),
    .axi4_mem_0_clock(),
    .axi4_mem_0_bits_aw_ready(axi4_mem_0_awready),
    .axi4_mem_0_bits_aw_valid(axi4_mem_0_awvalid),
    .axi4_mem_0_bits_aw_bits_id(axi4_mem_0_awid),
    .axi4_mem_0_bits_aw_bits_addr(axi4_mem_0_awaddr),
    .axi4_mem_0_bits_aw_bits_len(axi4_mem_0_awlen),
    .axi4_mem_0_bits_aw_bits_size(axi4_mem_0_awsize),
    .axi4_mem_0_bits_aw_bits_burst(axi4_mem_0_awburst),
    .axi4_mem_0_bits_aw_bits_lock(axi4_mem_0_awlock),
    .axi4_mem_0_bits_aw_bits_cache(axi4_mem_0_awcache),
    .axi4_mem_0_bits_aw_bits_prot(axi4_mem_0_awprot),
    .axi4_mem_0_bits_aw_bits_qos(axi4_mem_0_awqos),
    .axi4_mem_0_bits_w_ready(axi4_mem_0_wready),
    .axi4_mem_0_bits_w_valid(axi4_mem_0_wvalid),
    .axi4_mem_0_bits_w_bits_data(axi4_mem_0_wdata),
    .axi4_mem_0_bits_w_bits_strb(axi4_mem_0_wstrb),
    .axi4_mem_0_bits_w_bits_last(axi4_mem_0_wlast),
    .axi4_mem_0_bits_b_ready(axi4_mem_0_bready),
    .axi4_mem_0_bits_b_valid(axi4_mem_0_bvalid),
    .axi4_mem_0_bits_b_bits_id(axi4_mem_0_bid),
    .axi4_mem_0_bits_b_bits_resp(axi4_mem_0_bresp),
    .axi4_mem_0_bits_ar_ready(axi4_mem_0_arready),
    .axi4_mem_0_bits_ar_valid(axi4_mem_0_arvalid),
    .axi4_mem_0_bits_ar_bits_id(axi4_mem_0_arid),
    .axi4_mem_0_bits_ar_bits_addr(axi4_mem_0_araddr),
    .axi4_mem_0_bits_ar_bits_len(axi4_mem_0_arlen),
    .axi4_mem_0_bits_ar_bits_size(axi4_mem_0_arsize),
    .axi4_mem_0_bits_ar_bits_burst(axi4_mem_0_arburst),
    .axi4_mem_0_bits_ar_bits_lock(axi4_mem_0_arlock),
    .axi4_mem_0_bits_ar_bits_cache(axi4_mem_0_arcache),
    .axi4_mem_0_bits_ar_bits_prot(axi4_mem_0_arprot),
    .axi4_mem_0_bits_ar_bits_qos(axi4_mem_0_arqos),
    .axi4_mem_0_bits_r_ready(axi4_mem_0_rready),
    .axi4_mem_0_bits_r_valid(axi4_mem_0_rvalid),
    .axi4_mem_0_bits_r_bits_id(axi4_mem_0_rid),
    .axi4_mem_0_bits_r_bits_data(axi4_mem_0_rdata),
    .axi4_mem_0_bits_r_bits_resp(axi4_mem_0_rresp),
    .axi4_mem_0_bits_r_bits_last(axi4_mem_0_rlast),
    .ext_interrupts(ext_interrupts)
);

endmodule
