module rocket_wrapper(
    input         clock,
    input         reset,
    input         mem_axi4_0_awready,
    output        mem_axi4_0_awvalid,
    output  [3:0] mem_axi4_0_awid,
    output [31:0] mem_axi4_0_awaddr,
    output  [7:0] mem_axi4_0_awlen,
    output  [2:0] mem_axi4_0_awsize,
    output  [1:0] mem_axi4_0_awburst,
    output        mem_axi4_0_awlock,
    output  [3:0] mem_axi4_0_awcache,
    output  [2:0] mem_axi4_0_awprot,
    output  [3:0] mem_axi4_0_awqos,
    input         mem_axi4_0_wready,
    output        mem_axi4_0_wvalid,
    output [63:0] mem_axi4_0_wdata,
    output  [7:0] mem_axi4_0_wstrb,
    output        mem_axi4_0_wlast,
    output        mem_axi4_0_bready,
    input         mem_axi4_0_bvalid,
    input   [3:0] mem_axi4_0_bid,
    input   [1:0] mem_axi4_0_bresp,
    input         mem_axi4_0_arready,
    output        mem_axi4_0_arvalid,
    output  [3:0] mem_axi4_0_arid,
    output [31:0] mem_axi4_0_araddr,
    output  [7:0] mem_axi4_0_arlen,
    output  [2:0] mem_axi4_0_arsize,
    output  [1:0] mem_axi4_0_arburst,
    output        mem_axi4_0_arlock,
    output  [3:0] mem_axi4_0_arcache,
    output  [2:0] mem_axi4_0_arprot,
    output  [3:0] mem_axi4_0_arqos,
    output        mem_axi4_0_rready,
    input         mem_axi4_0_rvalid,
    input   [3:0] mem_axi4_0_rid,
    input  [63:0] mem_axi4_0_rdata,
    input   [1:0] mem_axi4_0_rresp,
    input         mem_axi4_0_rlast,
    input         mmio_axi4_0_awready,
    output        mmio_axi4_0_awvalid,
    output  [3:0] mmio_axi4_0_awid,
    output [30:0] mmio_axi4_0_awaddr,
    output  [7:0] mmio_axi4_0_awlen,
    output  [2:0] mmio_axi4_0_awsize,
    output  [1:0] mmio_axi4_0_awburst,
    output        mmio_axi4_0_awlock,
    output  [3:0] mmio_axi4_0_awcache,
    output  [2:0] mmio_axi4_0_awprot,
    output  [3:0] mmio_axi4_0_awqos,
    input         mmio_axi4_0_wready,
    output        mmio_axi4_0_wvalid,
    output [63:0] mmio_axi4_0_wdata,
    output  [7:0] mmio_axi4_0_wstrb,
    output        mmio_axi4_0_wlast,
    output        mmio_axi4_0_bready,
    input         mmio_axi4_0_bvalid,
    input   [3:0] mmio_axi4_0_bid,
    input   [1:0] mmio_axi4_0_bresp,
    input         mmio_axi4_0_arready,
    output        mmio_axi4_0_arvalid,
    output  [3:0] mmio_axi4_0_arid,
    output [30:0] mmio_axi4_0_araddr,
    output  [7:0] mmio_axi4_0_arlen,
    output  [2:0] mmio_axi4_0_arsize,
    output  [1:0] mmio_axi4_0_arburst,
    output        mmio_axi4_0_arlock,
    output  [3:0] mmio_axi4_0_arcache,
    output  [2:0] mmio_axi4_0_arprot,
    output  [3:0] mmio_axi4_0_arqos,
    output        mmio_axi4_0_rready,
    input         mmio_axi4_0_rvalid,
    input   [3:0] mmio_axi4_0_rid,
    input  [63:0] mmio_axi4_0_rdata,
    input   [1:0] mmio_axi4_0_rresp,
    input         mmio_axi4_0_rlast,
    output        l2_frontend_bus_axi4_0_awready,
    input         l2_frontend_bus_axi4_0_awvalid,
    input   [7:0] l2_frontend_bus_axi4_0_awid,
    input  [31:0] l2_frontend_bus_axi4_0_awaddr,
    input   [7:0] l2_frontend_bus_axi4_0_awlen,
    input   [2:0] l2_frontend_bus_axi4_0_awsize,
    input   [1:0] l2_frontend_bus_axi4_0_awburst,
    input         l2_frontend_bus_axi4_0_awlock,
    input   [3:0] l2_frontend_bus_axi4_0_awcache,
    input   [2:0] l2_frontend_bus_axi4_0_awprot,
    input   [3:0] l2_frontend_bus_axi4_0_awqos,
    output        l2_frontend_bus_axi4_0_wready,
    input         l2_frontend_bus_axi4_0_wvalid,
    input  [63:0] l2_frontend_bus_axi4_0_wdata,
    input   [7:0] l2_frontend_bus_axi4_0_wstrb,
    input         l2_frontend_bus_axi4_0_wlast,
    input         l2_frontend_bus_axi4_0_bready,
    output        l2_frontend_bus_axi4_0_bvalid,
    output  [7:0] l2_frontend_bus_axi4_0_bid,
    output  [1:0] l2_frontend_bus_axi4_0_bresp,
    output        l2_frontend_bus_axi4_0_arready,
    input         l2_frontend_bus_axi4_0_arvalid,
    input   [7:0] l2_frontend_bus_axi4_0_arid,
    input  [31:0] l2_frontend_bus_axi4_0_araddr,
    input   [7:0] l2_frontend_bus_axi4_0_arlen,
    input   [2:0] l2_frontend_bus_axi4_0_arsize,
    input   [1:0] l2_frontend_bus_axi4_0_arburst,
    input         l2_frontend_bus_axi4_0_arlock,
    input   [3:0] l2_frontend_bus_axi4_0_arcache,
    input   [2:0] l2_frontend_bus_axi4_0_arprot,
    input   [3:0] l2_frontend_bus_axi4_0_arqos,
    input         l2_frontend_bus_axi4_0_rready,
    output        l2_frontend_bus_axi4_0_rvalid,
    output  [7:0] l2_frontend_bus_axi4_0_rid,
    output [63:0] l2_frontend_bus_axi4_0_rdata,
    output  [1:0] l2_frontend_bus_axi4_0_rresp,
    output        l2_frontend_bus_axi4_0_rlast,
    input   [3:0] interrupts
);

ExampleRocketSystem rocket_inst(
    .clock(clock),
    .reset(reset),
    .debug_clockeddmi_dmi_req_ready(),
    .debug_clockeddmi_dmi_req_valid(1'b0),
    .debug_clockeddmi_dmi_req_bits_addr(7'b0),
    .debug_clockeddmi_dmi_req_bits_data(32'b0),
    .debug_clockeddmi_dmi_req_bits_op(2'b0),
    .debug_clockeddmi_dmi_resp_ready(1'b0),
    .debug_clockeddmi_dmi_resp_valid(),
    .debug_clockeddmi_dmi_resp_bits_data(),
    .debug_clockeddmi_dmi_resp_bits_resp(),
    .debug_clockeddmi_dmiClock(1'b0),
    .debug_clockeddmi_dmiReset(1'b0),
    .debug_ndreset(),
    .debug_dmactive(),
    .mem_axi4_0_aw_ready(mem_axi4_0_awready),
    .mem_axi4_0_aw_valid(mem_axi4_0_awvalid),
    .mem_axi4_0_aw_bits_id(mem_axi4_0_awid),
    .mem_axi4_0_aw_bits_addr(mem_axi4_0_awaddr),
    .mem_axi4_0_aw_bits_len(mem_axi4_0_awlen),
    .mem_axi4_0_aw_bits_size(mem_axi4_0_awsize),
    .mem_axi4_0_aw_bits_burst(mem_axi4_0_awburst),
    .mem_axi4_0_aw_bits_lock(mem_axi4_0_awlock),
    .mem_axi4_0_aw_bits_cache(mem_axi4_0_awcache),
    .mem_axi4_0_aw_bits_prot(mem_axi4_0_awprot),
    .mem_axi4_0_aw_bits_qos(mem_axi4_0_awqos),
    .mem_axi4_0_w_ready(mem_axi4_0_wready),
    .mem_axi4_0_w_valid(mem_axi4_0_wvalid),
    .mem_axi4_0_w_bits_data(mem_axi4_0_wdata),
    .mem_axi4_0_w_bits_strb(mem_axi4_0_wstrb),
    .mem_axi4_0_w_bits_last(mem_axi4_0_wlast),
    .mem_axi4_0_b_ready(mem_axi4_0_bready),
    .mem_axi4_0_b_valid(mem_axi4_0_bvalid),
    .mem_axi4_0_b_bits_id(mem_axi4_0_bid),
    .mem_axi4_0_b_bits_resp(mem_axi4_0_bresp),
    .mem_axi4_0_ar_ready(mem_axi4_0_arready),
    .mem_axi4_0_ar_valid(mem_axi4_0_arvalid),
    .mem_axi4_0_ar_bits_id(mem_axi4_0_arid),
    .mem_axi4_0_ar_bits_addr(mem_axi4_0_araddr),
    .mem_axi4_0_ar_bits_len(mem_axi4_0_arlen),
    .mem_axi4_0_ar_bits_size(mem_axi4_0_arsize),
    .mem_axi4_0_ar_bits_burst(mem_axi4_0_arburst),
    .mem_axi4_0_ar_bits_lock(mem_axi4_0_arlock),
    .mem_axi4_0_ar_bits_cache(mem_axi4_0_arcache),
    .mem_axi4_0_ar_bits_prot(mem_axi4_0_arprot),
    .mem_axi4_0_ar_bits_qos(mem_axi4_0_arqos),
    .mem_axi4_0_r_ready(mem_axi4_0_rready),
    .mem_axi4_0_r_valid(mem_axi4_0_rvalid),
    .mem_axi4_0_r_bits_id(mem_axi4_0_rid),
    .mem_axi4_0_r_bits_data(mem_axi4_0_rdata),
    .mem_axi4_0_r_bits_resp(mem_axi4_0_rresp),
    .mem_axi4_0_r_bits_last(mem_axi4_0_rlast),
    .mmio_axi4_0_aw_ready(mmio_axi4_0_awready),
    .mmio_axi4_0_aw_valid(mmio_axi4_0_awvalid),
    .mmio_axi4_0_aw_bits_id(mmio_axi4_0_awid),
    .mmio_axi4_0_aw_bits_addr(mmio_axi4_0_awaddr),
    .mmio_axi4_0_aw_bits_len(mmio_axi4_0_awlen),
    .mmio_axi4_0_aw_bits_size(mmio_axi4_0_awsize),
    .mmio_axi4_0_aw_bits_burst(mmio_axi4_0_awburst),
    .mmio_axi4_0_aw_bits_lock(mmio_axi4_0_awlock),
    .mmio_axi4_0_aw_bits_cache(mmio_axi4_0_awcache),
    .mmio_axi4_0_aw_bits_prot(mmio_axi4_0_awprot),
    .mmio_axi4_0_aw_bits_qos(mmio_axi4_0_awqos),
    .mmio_axi4_0_w_ready(mmio_axi4_0_wready),
    .mmio_axi4_0_w_valid(mmio_axi4_0_wvalid),
    .mmio_axi4_0_w_bits_data(mmio_axi4_0_wdata),
    .mmio_axi4_0_w_bits_strb(mmio_axi4_0_wstrb),
    .mmio_axi4_0_w_bits_last(mmio_axi4_0_wlast),
    .mmio_axi4_0_b_ready(mmio_axi4_0_bready),
    .mmio_axi4_0_b_valid(mmio_axi4_0_bvalid),
    .mmio_axi4_0_b_bits_id(mmio_axi4_0_bid),
    .mmio_axi4_0_b_bits_resp(mmio_axi4_0_bresp),
    .mmio_axi4_0_ar_ready(mmio_axi4_0_arready),
    .mmio_axi4_0_ar_valid(mmio_axi4_0_arvalid),
    .mmio_axi4_0_ar_bits_id(mmio_axi4_0_arid),
    .mmio_axi4_0_ar_bits_addr(mmio_axi4_0_araddr),
    .mmio_axi4_0_ar_bits_len(mmio_axi4_0_arlen),
    .mmio_axi4_0_ar_bits_size(mmio_axi4_0_arsize),
    .mmio_axi4_0_ar_bits_burst(mmio_axi4_0_arburst),
    .mmio_axi4_0_ar_bits_lock(mmio_axi4_0_arlock),
    .mmio_axi4_0_ar_bits_cache(mmio_axi4_0_arcache),
    .mmio_axi4_0_ar_bits_prot(mmio_axi4_0_arprot),
    .mmio_axi4_0_ar_bits_qos(mmio_axi4_0_arqos),
    .mmio_axi4_0_r_ready(mmio_axi4_0_rready),
    .mmio_axi4_0_r_valid(mmio_axi4_0_rvalid),
    .mmio_axi4_0_r_bits_id(mmio_axi4_0_rid),
    .mmio_axi4_0_r_bits_data(mmio_axi4_0_rdata),
    .mmio_axi4_0_r_bits_resp(mmio_axi4_0_rresp),
    .mmio_axi4_0_r_bits_last(mmio_axi4_0_rlast),
    .l2_frontend_bus_axi4_0_aw_ready(l2_frontend_bus_axi4_0_awready),
    .l2_frontend_bus_axi4_0_aw_valid(l2_frontend_bus_axi4_0_awvalid),
    .l2_frontend_bus_axi4_0_aw_bits_id(l2_frontend_bus_axi4_0_awid),
    .l2_frontend_bus_axi4_0_aw_bits_addr(l2_frontend_bus_axi4_0_awaddr),
    .l2_frontend_bus_axi4_0_aw_bits_len(l2_frontend_bus_axi4_0_awlen),
    .l2_frontend_bus_axi4_0_aw_bits_size(l2_frontend_bus_axi4_0_awsize),
    .l2_frontend_bus_axi4_0_aw_bits_burst(l2_frontend_bus_axi4_0_awburst),
    .l2_frontend_bus_axi4_0_aw_bits_lock(l2_frontend_bus_axi4_0_awlock),
    .l2_frontend_bus_axi4_0_aw_bits_cache(l2_frontend_bus_axi4_0_awcache),
    .l2_frontend_bus_axi4_0_aw_bits_prot(l2_frontend_bus_axi4_0_awprot),
    .l2_frontend_bus_axi4_0_aw_bits_qos(l2_frontend_bus_axi4_0_awqos),
    .l2_frontend_bus_axi4_0_w_ready(l2_frontend_bus_axi4_0_wready),
    .l2_frontend_bus_axi4_0_w_valid(l2_frontend_bus_axi4_0_wvalid),
    .l2_frontend_bus_axi4_0_w_bits_data(l2_frontend_bus_axi4_0_wdata),
    .l2_frontend_bus_axi4_0_w_bits_strb(l2_frontend_bus_axi4_0_wstrb),
    .l2_frontend_bus_axi4_0_w_bits_last(l2_frontend_bus_axi4_0_wlast),
    .l2_frontend_bus_axi4_0_b_ready(l2_frontend_bus_axi4_0_bready),
    .l2_frontend_bus_axi4_0_b_valid(l2_frontend_bus_axi4_0_bvalid),
    .l2_frontend_bus_axi4_0_b_bits_id(l2_frontend_bus_axi4_0_bid),
    .l2_frontend_bus_axi4_0_b_bits_resp(l2_frontend_bus_axi4_0_bresp),
    .l2_frontend_bus_axi4_0_ar_ready(l2_frontend_bus_axi4_0_arready),
    .l2_frontend_bus_axi4_0_ar_valid(l2_frontend_bus_axi4_0_arvalid),
    .l2_frontend_bus_axi4_0_ar_bits_id(l2_frontend_bus_axi4_0_arid),
    .l2_frontend_bus_axi4_0_ar_bits_addr(l2_frontend_bus_axi4_0_araddr),
    .l2_frontend_bus_axi4_0_ar_bits_len(l2_frontend_bus_axi4_0_arlen),
    .l2_frontend_bus_axi4_0_ar_bits_size(l2_frontend_bus_axi4_0_arsize),
    .l2_frontend_bus_axi4_0_ar_bits_burst(l2_frontend_bus_axi4_0_arburst),
    .l2_frontend_bus_axi4_0_ar_bits_lock(l2_frontend_bus_axi4_0_arlock),
    .l2_frontend_bus_axi4_0_ar_bits_cache(l2_frontend_bus_axi4_0_arcache),
    .l2_frontend_bus_axi4_0_ar_bits_prot(l2_frontend_bus_axi4_0_arprot),
    .l2_frontend_bus_axi4_0_ar_bits_qos(l2_frontend_bus_axi4_0_arqos),
    .l2_frontend_bus_axi4_0_r_ready(l2_frontend_bus_axi4_0_rready),
    .l2_frontend_bus_axi4_0_r_valid(l2_frontend_bus_axi4_0_rvalid),
    .l2_frontend_bus_axi4_0_r_bits_id(l2_frontend_bus_axi4_0_rid),
    .l2_frontend_bus_axi4_0_r_bits_data(l2_frontend_bus_axi4_0_rdata),
    .l2_frontend_bus_axi4_0_r_bits_resp(l2_frontend_bus_axi4_0_rresp),
    .l2_frontend_bus_axi4_0_r_bits_last(l2_frontend_bus_axi4_0_rlast),
    .interrupts(interrupts)
);

endmodule
